# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinflixer_liked_movie_movie', to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Liked_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinflixer_liked_user_movie', to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Tinflixer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('first_name', models.CharField(default='first name', max_length=20)),
                ('last_name', models.CharField(default='last name', max_length=20)),
                ('new', models.BooleanField(default=True)),
                ('email', models.CharField(default='example@example.com', max_length=30)),
                ('low_age', models.IntegerField(blank=True, null=True)),
                ('high_age', models.IntegerField(blank=True, null=True)),
                ('real_age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liked_user',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinflixer_liked_user_user1', to='tinflixer.Tinflixer'),
        ),
        migrations.AddField(
            model_name='liked_user',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinflixer_liked_user_user2', to='tinflixer.Tinflixer'),
        ),
        migrations.AddField(
            model_name='liked_movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinflixer_liked_movie_user', to='tinflixer.Tinflixer'),
        ),
    ]
